name: py_test
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.17.0
  - matplotlib=3.1.2
  - matplotlib-base=3.2.1
  - numpy=1.18.1
  - pandas=1.0.3
  - requests=2.23.0
  -pip:
    - svgpath2mpl=0.2.1
